title: <p align="center"> Julio Iglesias </p>

logo: "assets/img/julio.jpg"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/fabriziocominetti/">LinkedIn</a> |
  <a href="cv/Julio_cv.pdf">cv</a>
  </p>
  
  <p align="center">
  <img src="https://readme-typing-svg.herokuapp.com?font=Lato&weight=700&size=22&pause=1000&color=500000&center=true&vCenter=true&width=450&lines=Hi+Everyone!+%F0%9F%91%8B;Welcome+to+my+portfolio+website!" alt="Typing SVG" />
  <br />
  ðŸ“Œ Data Science at <i>Universidad Complutense de Madrid</i>
  <br />
  ðŸ“Œ Digital Editor at <i>AC Milan</i>
  </p>
  
theme: jekyll-theme-minimal



















